<a href="https://colab.research.google.com/github/raulbenitez/image_processing/blob/master/short_paths_binary_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
from skimage.graph import route_through_array

image = np.array([[1, 3], [10, 12]])
# Forbid diagonal steps
route_through_array(image, [0, 0], [1, 1], fully_connected=False)
([(0, 0), (0, 1), (1, 1)], 9.5)
# Now allow diagonal steps: the path goes directly from start to end
route_through_array(image, [0, 0], [1, 1])
([(0, 0), (1, 1)], 9.19238815542512)
# Cost is the sum of array values along the path (16 = 1 + 3 + 12)
route_through_array(image, [0, 0], [1, 1], fully_connected=False,geometric=False)
# Larger array where we display the path that is selected
image = np.arange((36)).reshape((6, 6))

# Find the path with lowest cost
indices, weight = route_through_array(image, (0, 0), (5, 5))
indices = np.stack(indices, axis=-1)
path = np.zeros_like(image)
path[indices[0], indices[1]] = 1
path




array([[ 1,  3],
       [10, 12]])

In [4]:
import numpy as np
import skimage.graph

T,F = True,False
array = np.asarray(
    [[T, F, F, T],
     [T, T, F, T],
     [F, T, T, F],
     [T, T, T, T]])
costs = np.where(array, 1, 1000)
path, cost = skimage.graph.route_through_array(costs, start=(0,0), end=(3,3), fully_connected=True)

path

[(0, 0), (1, 1), (2, 2), (3, 3)]

In [5]:
array

array([[ True, False, False,  True],
       [ True,  True, False,  True],
       [False,  True,  True, False],
       [ True,  True,  True,  True]])

In [6]:
costs

array([[   1, 1000, 1000,    1],
       [   1,    1, 1000,    1],
       [1000,    1,    1, 1000],
       [   1,    1,    1,    1]])